#!/usr/bin/env bash
set -euo pipefail
home-manager-update
if [ -n "${WORKSPACE_FOLDER:-}" ]; then
  cd "$WORKSPACE_FOLDER"
  nix develop --command -- echo "Post start hook: Prepared env for $WORKSPACE_FOLDER"
fi
