#!/usr/bin/env bash
set -euo pipefail

cd ~/.config/home-manager
git fetch origin
git reset --hard origin/main
if command -v home-manager &>/dev/null; then
    home-manager switch --flake ".#$USER" --impure -b backup
else
    nix run .#homeConfigurations."$USER".activationPackage
fi
